name: Feature request
description: Suggest an idea for products
type: Feature
assignees:
  - jimmy-chen-db
body:
  - type: textarea
    id: feature
    attributes:
      label: Feature/Solution you'd like to see
      description: A clear and concise description of the feature desired or the lack of it.
    validations:
      required: true
  - type: textarea
    id: functional_specification
    attributes:
      label: Functional Specification
      description: A detailed specification of the feature's behavior, inputs, outputs, and constraints.
    validations:
      required: false
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: The criteria that must be met for the feature to be considered complete.
    validations:
      required: true
  - type: textarea
    id: design_considerations
    attributes:
      label: Design & Implementation Considerations
      description: Considerations for the design and implementation of the feature.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
