name: Feature request
description: Suggest an idea for products
assignees:
  - jimmy-chen-db
body:
  - type: textarea
    id: feature
    attributes:
      label: Feature
      description: A clear and concise description of the feature desired or the lack of it.
    validations:
      required: true
  - type: dropdown
    id: product
    attributes:
      label: Product(s) and version if known
      multiple: true
      options:
        - eCTD Viewer 6.x
        - ecTD Viewer 7.x
        - eCTD Viewer 8.x
        - RADARS/Enterprise Edition
        - eCTD Publisher
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    id: design
    attributes:
      label: Design & Implementation Considerations
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
