name: Support request
description: Submit a support request
type: Support Request
assignees: []
body:
  - type: textarea
    id: support_request_description
    attributes:
      label: Support request description
      description: A clear and concise description of the support request.
    validations:
      required: true
  - type: dropdown
    id: affected_product
    attributes:
      label: Affected products and versions if known
      multiple: true
      options:
        - eCTD Viewer 6.x
        - eCTD Viewer 7.x
        - eCTD Viewer 8.x
        - eCTD Publisher 2.x
        - Phoenix Server 6.x
        - Other
    validations:
      required: false
  - type: input
    id: company_name
    attributes:
      label: Company name
      description: The company name associated with this request.
    validations:
      required: true
  - type: input
    id: contact_name
    attributes:
      label: Contact name
      description: The name of the contact associated with this request.
    validations:
      required: false
  - type: input
    id: contact_email
    attributes:
      label: Contact email
      description: The email address of the contact associated with this request.
    validations:
      required: false
